# Site
repository: sproogen/resume-theme
favicon: images/integration_icon_216462.ico

# Content configuration version
version: 2

# Personal info
name: Tyron Esch
title: Senior Integration Specialist 
email: tyronesch@gmail.com
#website: https://github.com/tyty-the-eyety

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  tyty-the-eyety
linkedin_username: tyron-esch

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "G-ZRSPGH85CH"

# About Section
# about_title: About Me
about_profile_image: images/Nqq42LCQ.jpeg
about_content: | # this will include new lines to allow paragraphs
  I have over a decade in the IT industry specialising in the systems integration environment with the IBM toolset, with my primary focus on IBM Integration Bus (IIB) and now App Connect Enterprise (ACE) and a vast knowledge of IBM MQ and experience on IBM DataPower XI52’s. I have a great intrest in the modernising of systems using Devops principles where I find the automation of deployments and montioring of the systems, infrastructure and integration scenarios of most intrest.

  I started my career at Standard Bank South Africa in 2008, where I began working on the IBM WebSphere Message Broker version 6 alongside SAP XI. The very first production implementation I was involved in was a few months later where we had to upgrade the version to Message Broker 6.1. I was involved in many more implementations and leading many in the years to come. I was involved in the greater Core Banking project, which was the transformation of the bank from legacy CRM and Bank Accounts to SAP systems, that was divided into many sequential releases, in which I was involved in the architecture, design and implementation of solutions on the Enterprise Service Bus using SOA and API integration patterns and principles of the core banking system and many other bespoke integration scenarios for banking functionality. 

  In 2016 I joined a new company, i1 Solutions, looking to broaden my technical and interpersonal skills. i1 Solutions is an IBM Platinum partner in South Africa that consults to many different industries with IBM Integration as their core focus. The idea of working on many different clients and learning of the different ways other systems are implemented and having the chance to be involved in designing and architecting many of them was also a massive attraction. During my tenure at i1 Solutions I gained knowledge of not only more technical skills and the way other implementations of and ESB but also with the soft skills of liaise with clients and their needs of their business and applications.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        #title: Implementation of Bamboo, Jenkins
        description: | # this will include new lines to allow paragraphs
           Integration Skills: <b>IBM IIB/ACE</b> , <b>IBM MQ</b> and <b> IBM WebSphere DataPower</b> <br> My Other Skills: <b>Windows</b> , <b>Linux (Ubuntu, Red Hat)</b>, <b>Java</b>, <b>ESQL</b>, <b>Bash</b>, <b>SQL</b>, <b>Docker</b>, <b>Python</b> <br> Protocals And Standards Skills: <b>XML</b> , <b>WSDL/SOAP</b>, <b>XPath</b>, <b>JSon</b>, <b>REST</b>, <b>SWAGGER</b>, <b>TCP/IP/UDP</b>, <b>HTTPs/SSL/TLS</b> <br> Tools:  <b>Subversion/SVN</b>, <b>GIT</b>, <b>BitBucket</b>, <b>CVS</b>, <b>Jira(Atlassian  Suit)</b>, <b>Bamboo</b>, <b>Jenkins</b>, <b>Postman</b>, <b>SOAPUI</b> <br>

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        
        description: | # this will include new lines to allow paragraphs
          <ul>
            <li>DevOps on AWS</li>
            <ul>
              <li>AWS Cloud Technical Essentials</li>
              <li>DevOps on AWS: Code, Build, and Test</li>
              <li>DevOps on AWS: Release and Deploy</li>
              <li>DevOps on AWS: Operate and Monitor</li>
            </ul>
            <li>IBM Certified Solution Developer - APP Connect Enterprise V11</li>
            <li>IBM Certified System Administrator - MQ V9.0</li>
            <li>IBM Certified Solution Developer - Integration Bus V9.0 </li>
            <li>IBM Certified System Administrator - MQ V8.0</li>
            <li>IBM WebSphere Cast Iron Technical Sales Professional v1</li>
          </ul>


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Implementation of Bamboo, Jenkins
        description: | # this will include new lines to allow paragraphs
          I took responsibility of implementing a continuous integration and deployment engine for one of my major clients to reduce the amount of time, errors and increase the repeatability of deployments therefore reducing risk. I first started doing this in my own time as I saw a great need for it and work projects were taking priority. My first choice was Atlassian Bamboo which worked well, and I had used it before, and the interface layout was very intuitive. Except for the fact that in Q1 2021 no more releases would be available. I then decided to move the CI/CD of Jenkins to build IIB/ACE Applications where it soon grew to include MQ mqsc scripts, DB tables, and now other Java based application owners are using the same platform.
          

      - layout: top-middle
        title: Implementation of Node and Flow Statistics on IIB for problem resolution 
      
        description: | # this will include new lines to allow paragraphs
           By implementing flow and node stats, I was able trouble shoot problems of poor performance. I was able to not only identify a slowdown from one of our sites and quantify it, then narrow it down to a Data Base call on a compute node using node stats. I was able determine that it was a network slowdown from one site to another and come up with multiple different solutions to help alleviate the problem. The difference between sites flow stats was 900 milliseconds compared to 80 milliseconds on the first site. This was more then 10x the time it should be taken.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: i1 Solutions
        link: https://www.i1solutions.co.za/
        link_text: i1 Solutions
        sub_title: Senior Integration Developer
        caption: April 2016 - July 2022
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           At i1 my main client was Aspen Pharmaceuticals where I architected the integration and MQ systems as well as developed, supported, and monitored the IBM Integration Stack. This included IIB/ACE , MQ ,DB2 and the GSCP (a custom web portal for Supply Chain). I would meet with the client from their business and technical team were I designed and architected the integration scenarios and API's.
           I have also implemented and maintained multiple Continuous Delivery implementations, namely Bamboo and Jenkins, where IIB/ACE bar files would be built and deployed using committed code and configurations. I also implemented MQ and DB2 configuration tables as part of the Continuous Delivery implementation. This made it possible to implement and supported business critical systems and processes quickly and efficiently on the BaaN so SAP migration projects of the multiple ERP systems in the Aspen environment. 
           
           Other Clients Included:
           <ul>
             <li>Woolworths</li>
             <ul>
               <li>Involved in upgrade projects and code rewrite and optimisation</li>
               <li>Wrote the new standards document where naming standards were agreed with the client and the coding standards</li>
               <li>Review code was according to standards</li>
             </ul>
             <li>Telesure</li>
             <ul>
               <li>Support of Production Environments</li>
               <li>IIB and MQ Administrative Tasks</li>
               <li>IIB Environmental Support</li>
             </ul>
             <li>Spar</li>
             <ul>
               <li>Support of Production Environments</li>
               <li>IIB and MQ Administrative Tasks</li>
               <li>Implement keystores for IIB and MQ to ensure Secure Communication to 3rd Parties</li>
             </ul>
             <li>Old Mutual</li>
             <ul>
               <li>Assisted the client team  when there were project deadlines that needed to be met</li>
               <li>Creating new IIB Rest and Web Services</li>
             </ul>
             <li>Cash Connect</li>
             <ul>
               <li>Implemented IBM MQ</li>
               <li>Supported the MQ environment that connected to their chosen Banking partner</li>
             </ul>
           </ul>
           


      - layout: left
        title: Standard Bank South Africa
        link: https://www.standardbank.co.za/southafrica/personal/home
        link_text: Standard Bank
        sub_title: Senior Integration Specialist 
        caption: February 2008 - May 2016
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           I worked at Standard Bank for 8 years as a developer and worked my way up to Integration Specialist in the Personal and Business Banking (PBB) ESB Integration team.  I was involved in implementing many projects including 5 major Core Banking releases, where I was a technical lead for Message Broker and in the latter projects DataPower as well. I also assisted in the building of the Message Broker on the Mainframe, which included code changes to deal with Mainframe code page differences. I also consulted in the Africa and Corparate and Investment Integration Teams in assisting in problem resolution and solution design of the decommissioning of the legacy integration products and systems to IBM Message Broker and DataPower.
           

#
#  - title: Education # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: 
#        caption: 2008 - 2016
#        sub_title: BSc Computer Science

#        description: | # this will include new lines to allow paragraphs
#          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in IT some of my other interests and hobbies are:
      - 3D Printing <br>
        I bought myself a 3D Printer as a present to myself and have dived deep into the printing world. 3D printing shows one how to be a logical thinker and problem-solving skills, there is so much to learn not just in the setting up and maintaince of the printer but in teaching yourself new skills like CAD software.
      - DIY <br>
        Owning a house ensures one should have some sort of do it yourself skills, and the sense of ownership and accomplishment that someone gets by building their own furniture or fixing something that is broken is a reward on itself. 
      - Gaming <br>
      


#      Look at this cool image  
#      ![Trees](landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
